export { IcChevron } from './IcChevron'
export { IcMenu } from './IcMenu'
export { IcPencil } from './IcPencil'
export { IcSpinner } from './IcSpinner'
export { IcTrash } from './IcTrash'
export { IcUser } from './IcUser'
